### ISSUE TITLE
Evaluate MiniLLM Performance

### ISSUE THREAD

**Issue by dasgoutam** [digitalfabrik/integreat-chat#10]
Given a consistent retrieval mechanism, evaluate the performance of MiniLLM's

Select a list of MiniLLM's to evaluate and compare performances. 

At a later stage, the 'best performing' MiniLLM can be used to compare with larger models(higher parameters)

**Comment by svenseeberg** [comment]
Currently implemented in Google Colab.

**Comment by svenseeberg** [comment]
Maybe we can use llama3.2:3b to classify the incoming messages as "question"/"not a question".

**Comment by svenseeberg** [comment]
> Maybe we can use llama3.2:3b to classify the incoming messages as "question"/"not a question".

https://github.com/digitalfabrik/integreat-chat/blob/main/integreat_chat/core/settings.py#L54-L56
