### ISSUE TITLE
Random chance for showing chatbot

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-chat#13]
Add a feature flag whether the chat is enabled at all.
Also add a value for how many percent of users should get the chatbot displayed.
Needs to be a region setting probably.

**Comment by svenseeberg** [comment]
https://github.com/digitalfabrik/integreat-cms/pull/2738#issuecomment-2124112802

**Comment by steffenkleinle** [comment]
Is there an issue for implementation in the cms?

**Comment by svenseeberg** [comment]
https://github.com/digitalfabrik/integreat-cms/pull/2856
