### ISSUE TITLE
Answer author information

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-chat#14]
Automatically generated answers should show a little bot Icon (🤖) in the upper right corner of a message in the Integreat App.

App issue: https://github.com/digitalfabrik/integreat-app/issues/2945

**Comment by svenseeberg** [comment]
Based on https://github.com/digitalfabrik/integreat-chat/issues/17#issuecomment-2343570362 we can use the subject of an article to differentiate between automatic and manual answers. However, we should transform this information into a better attribute for the App in the API v3. Something like `auto_generated: True|False`.

**Comment by svenseeberg** [comment]
Answers should contain a `automatic_answer` attribute: https://github.com/digitalfabrik/integreat-cms/blob/develop/integreat_cms/api/v3/chat/zammad_api.py#L99

**Comment by svenseeberg** [comment]
This is important for EU AI Act compliance, see #53

**Comment by steffenkleinle** [comment]
Could we perhaps expose the name of the author in the API? I think that would be a nice addition.
Also see https://github.com/digitalfabrik/integreat-app/issues/2945#issuecomment-2428361085.

**Comment by svenseeberg** [comment]
> Could we perhaps expose the name of the author in the API?

In theory we could. But I'd be careful with that feature right now. I fear that this would reduce acceptance in our partner regions.
