### ISSUE TITLE
Check document relevance

### ISSUE THREAD

**Issue by dasgoutam** [digitalfabrik/integreat-chat#57]
We can try to check the relevance of retrieved documents to the question by passing it through an llm with a particular prompt

**Comment by dasgoutam** [comment]
Prompt for LLM: "You are a grader assessing relevance of a retrieved document to a user question. If the document contains keyword(s) or semantic meaning related to the user question, grade it as relevant. It does not need to be a stringent test. The goal is to filter out erroneous retrievals. Give a binary score 'yes' or 'no' score to indicate whether the document is relevant to the question."

**Comment by svenseeberg** [comment]
We should change our procedure like that:
- retrieve up to 5 documents from the vector database (keep the cutoff at a score of 1.3)
- sort documents by score
- ask LLM whether the document is relevant for the question (if activated) and return the first 3 documents that are relevant
- if the "relevance check" is deactivated, we just return the 3 documents with the lowest score/distance

**Comment by dasgoutam** [comment]
Implemented in #59. The relevancy check is for all retrieved documents and not 3 documents for now
