### ISSUE TITLE
Select & set up vector database

### ISSUE THREAD

**Issue by svenseeberg** [digitalfabrik/integreat-chat#7]
Install either https://github.com/milvus-io/milvus or https://github.com/weaviate/weaviate

**Comment by dasgoutam** [comment]
I tried out the following vector databases which work well- 

1. Weaviate - https://weaviate.io
3. PGVector - https://github.com/pgvector/pgvector
4. Faiss (Not exactly a database. Good for local testing)
5. Milvus (This seems to be quite popular. However I had some difficulty setting this up for some reason) - https://milvus.io

Some other options I haven't tried out - 
1. Chroma
2. QDrant

**Comment by svenseeberg** [comment]
pgvector would be really nice. It is already packaged for Debian (https://packages.debian.org/sid/postgresql-15-pgvector). It is still in the unstable branch, but there is hope that it will end up in backports or testing at some point.

**Comment by svenseeberg** [comment]
Weaviate is also okay. Deploying a Go binary should be quite easy. And 3 clause MIT license is also good.

**Comment by svenseeberg** [comment]
Milvus has a very good license with Apache 2.0 and seems to have the largest community so far.

**Comment by svenseeberg** [comment]
https://github.com/chroma-core/chroma is using Python. I'm a bit worried about performance. But there are also Rust components etc. So maybe this is not an issue? Apache 2.0 licsense again is very suitable. Community is definitely smaller than Milvius.

**Comment by svenseeberg** [comment]
QDrant is almost completely written in Rust and Apache 2.0 licensed. Community has the same size as Chroma or Weaviate. Smaller than Milvius though..

**Comment by svenseeberg** [comment]
Lets narrow it down to Weaviate and Milvus.

**Comment by svenseeberg** [comment]
Current state:
- Deployment of Milvus with docker-compose works
- Building milvus to have an executable does not really work
- Starting a weaviate process with the binary does not work as the network configuration parameters are not parsed as they should (when reading the documentation)
